### PR TITLE
- Added limits on selected fields.

### PR DESCRIPTION
**Pull request by theall38103**
Limit the length of a description (3999), length of a given reference (500), and the number of references (500).

### CODE REVIEW

**Comment by kurtseifried** [comment]
I think this is reasonable for now but would like to expand it in future, especially as we get more descriptions than just the global one.

**Comment by lcashdol** [comment]
Hi All,

I feel like I'm reinventing the wheel, do folks have sample code of python or php working with the Mitre JSON 4.0 format?

Thanks
-Larry

**Comment by zdi-team** [comment]
@lcashdol sample code for creating the json or validating the json?

**Comment by zdi-team** [comment]
> Limit the length of a description (3999), length of a given reference (500), and the number of references (500).

Did we check that all the old descriptions will fit inside the new limit? I remember there was a lot of discussion about 2-3 years ago about this and I remember some folks had some very long descriptions. The definition of "very long" I don't recall exactly however.

**Comment by jwhitmore-mitre** [comment]
This is an old conversion, and is out of date. The description and reference limits have be in the 4.0 schema for some time now.

The new 5.0 schema in discussion can be found here: https://github.com/CVEProject/automation-working-group/tree/master/cve_json_schema/v5.x_discuss. 

There is not 4.0 validator that I know of. There is a simple validator for 5.0 under the v5.x_discuss. It's a python 3 script. 

I do not know of a CVE JSON generator but there are applications that output CVEs in compliant JSON format. There are not available a simple command line script.

**Comment by zdi-team** [comment]
@jwhitmore-mitre ah ok. Lew mentioned issue 44 in the agenda, but I realize now he must be referring to another repo

**Comment by lcashdol** [comment]
@zdi-team Hi, Sorry, Creating the JSON.

**Pull request merged**
