### PR TITLE
Add definitions to values of affected field and add unknown status

### PR DESCRIPTION
**Pull request by chandanbn**
based on action item from Oct 15th AWG meeting.

### CODE REVIEW

**Comment by chandanbn** [comment]
Can you approve this pull request?

That's one small character for schema, one giant leap for making CVE descriptions complete!

**Comment by kernelsmith** [comment]
If/when this gets accepted, we should consider removing the version info from the description since a) it's  duplicated and b) the version data here would be far too complex to include in the description.

**Comment by chandanbn** [comment]
> If/when this gets accepted, we should consider removing the version info from the description since a) it's duplicated and b) the version data here would be far too complex to include in the description.

I think there is a value in having a field that has a human readable and self standing description of the vulnerability. The description can be auto generated (as in Vulnogram) from the version data fields. Descriptions can become complex for vulnerabilities that affect a lot of different versions, but at least one does not have to type the same details again.

**Comment by chandanbn** [comment]
Sending a PING.

It has been six months since this change was submitted.
Is anyone on who owns this repo getting this notification?

**Pull request merged**
