### PR TITLE
Add a 99.9% correct email regexp.

### PR DESCRIPTION
**Pull request by todb-r7**
See http://emailregex.com/ and give yourself over to the madness that is
email regular expression testing.

### CODE REVIEW

**Comment by theall38103** [comment]
I think there may be two problems here : 

- The pattern does not appear to be anchored at the start and end.
- The escapes need to be doubled up.

**Comment by todb-r7** [comment]
Indeed you're correct, @theall38103 . Scrolling down a bit on http://emailregex.com/ I see a more javascript-specific one, which might do better (like the last, I haven't tested this yet either):

```javascript
/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
```

I was mainly concerned because the shipping version doesn't appear to account for +'s in email addresses, like `todb+cvespam@gmail.com`, which I completely expect to find in these submissions. But why solve that problem when we can way over-engineer the solution? :)

**Comment by todb-r7** [comment]
All right @theall38103 , give this version a shot. It's more sane.

**Comment by theall38103** [comment]
Sorry for the delay, Tod...

The latest regex you have should work for the most part. One question, though, do we need the non-capturing group for the domain part (ie, "(?:")?

**Comment by todb-r7** [comment]
Eh, the non-capturing business is pretty habitual for people who are concerned about memory management when it comes to capture groups. It certainly doesn't hurt -- it's not like you're using the results anywhere, anyway.

**Comment by kurtseifried** [comment]
Suggest we reject and move this check to a more appropriate place in the checks, e.g. business logic (e.g. Python/etc has a ton of libraries to validate emails, including things like making sure they have a valid IP or MX record for the domain). I'm thinking roughly:

1) Check commit is signed properly, matches CVE/CNA block/etc.
2) Check commit is smaller than overall size X (100 megs?)
3) Check entry is JSON valid at all
4) Figure out what kind of entry it is (load and look for STATE)
5) Depending on STATE run it through the schema parsers
6) Apply business logic, checks (e.g. proper email, URLs have working domains, etc. possibly actually get them and put them into archive.org and so on), we'll need some sort of ruleset for this
7) auto merge based on rules, require human, whatever

**Comment by todb-r7** [comment]
Fine by me. Rolling one's own email regexp will lead to sanity loss.

**Pull request closed without merging**
